
# Mock Data for Categories and Popularity
MODULE_CATEGORIES = {
    # Data Science
    'numpy': 'Data Science',
    'pandas': 'Data Science',
    'matplotlib': 'Data Science',
    'seaborn': 'Data Science',
    'bokeh': 'Data Science',
    'plotly': 'Data Science',
    'scipy': 'Data Science',
    'statsmodels': 'Data Science',
    'xgboost': 'Data Science',
    'sqlalchemy': 'Data Science',
    'peewee': 'Data Science',
    'pymongo': 'Data Science',
    'redis': 'Data Science',
    'databases': 'Data Science',
    'sqlobject': 'Data Science',
    'arrow': 'Data Science',
    'python-dotenv': 'Data Science',
    'pydantic': 'Data Science',
    'dataclasses': 'Data Science',
    'pyyaml': 'Data Science',
    'hypothesis': 'Data Science',
    'tox': 'Data Science',
    'mock': 'Data Science',
    'pdb': 'Data Science',
    'ipdb': 'Data Science',
    'click': 'Data Science',
    'typer': 'Data Science',
    'loguru': 'Data Science',
    'colorama': 'Data Science',
    

    # Web Development
    'requests': 'Web Development',
    'flask': 'Web Development',
    'django': 'Web Development',
    'fastapi': 'Web Development',
    'tornado': 'Web Development',
    'bottle': 'Web Development',
    'aiohttp': 'Web Development',
    'httpx': 'Web Development',
    'beautifulsoup4': 'Web Development',
    'scrapy' : 'Web Development',
    'requests-html' : 'Web Development',
    'mechanize' : 'Web Development',
    'pyquery' : 'Web Development',
    'scrapy-splash' : 'Web Development',
    'py2neo' : 'Web Development',
    'paramiko' : 'Web Development',
    'asyncio' : 'Web Development',
    'pygtk' : 'Web Development',
    'pyglet' : 'Web Development',
    'pyqtgraph' : 'Web Development',
    'sh' : 'Web Development',
     'websocket-client' : 'Web Development',
     'cherrypy': 'Web Development',
     'falcon': 'Web Development',
     'turbogears2': 'Web Development',
     'pyramid': 'Web Development',
     'web2py': 'Web Development',
     'trio-websocket':'Web Development',
     
    
    
    # Machine Learning
    'scikit-learn': 'Machine Learning',
    'tensorflow': 'Machine Learning',
    'keras': 'Machine Learning',
    'torch': 'Machine Learning',
    'xgboost': 'Machine Learning',
    'catboost': 'Machine Learning',
    'lightgbm': 'Machine Learning',
    'fastapi': 'Machine Learning',
    'celery': 'Machine Learning',
    'textblob': 'Machine Learning',
    'statsmodels': 'Machine Learning',
    'nltk': 'Machine Learning',
    'word2vec': 'Machine Learning',
    'jax':'Machine Learning',
    'eli5':'Machine Learning',
    'gernism':'Machine Learning',
    'spacy':'Machine Learning',
    'bert':'Machine Learning',
    'polyglot':'Machine Learning',
    'transformers':'Machine Learning',
    
    
    
    #Sound Outputs
    
    'PyAudio': 'Sound Output',
    'pydub': 'Sound Output',
    'sounddevice': 'Sound Output',
    'pygame': 'Sound Output',
    'playsound': 'Sound Output',
    'audioread': 'Sound Output',
    'pyaudio': 'Sound Output',
    'soundfile': 'Sound Output',
    'simpleaudio': 'Sound Output',
    'wave': 'Sound Output',
    'vosk' : 'Sound Output',
    
    #Speech Recognition(Speech-to-Text)
    'SpeechRecognition' : 'Speech Recognition',
    'pocketsphinx' : 'Speech Recognition',
    'Google Speech-to-Text' : 'Speech Recognition',
    'Microsoft Azure Speech Service' : 'Speech Recognition',
    
    #Speech Synthesis (Text-to-Speech)
    'pyttsx3' : 'Speech Synthesis',
    'gTTS' : 'Speech Synthesis',
    'SpeechRecognition' : 'Speech Synthesis',
    # '' : 'Speech Synthesis',
    # '':'Synthesis',
    
    
    #Databases
    'pymongo': 'Databases',
    'pymysql': 'Databases',
    'redis-py': 'Databases',
    'happybase': 'Databases',
    'psycopg2': 'Databases',
    'sqlalchemy': 'Databases',
    
    #Networking 
    'twisted' : 'Networking',
    'pysocks' : 'Networking',
    'websockets' : 'Networking',
    'paramiko' : 'Networking',
    
    
    #Security
    'pyopenssl':'Security',
    'yara-python':'Security',
    'scapy':'Security',
    'pycrypto':'Security',
    
    #IoT Development
    'bleak':'IoT Development', 
    'paho-mqtt':'IoT Development',         
    'zigpy':'IoT Development',  
    'circiutpython':'IoT Development',
    'micropython':'IoT Development',    
    
    #GUI Development
    'pyqt5': 'GUI Development',
    'tkinter': 'GUI Development',
    'customtkinter': 'GUI Development',
    'kivy': 'GUI Development',
    'pyforms': 'GUI Development',
    'pyautogui': 'GUI Development',
    'wxpython': 'GUI Development',
    'pyside6': 'GUI Development',
    
     # EDENDED HERE.
    #######################
    
    
   
    #Data Processing
    'pandas':'Data Processing',
    'polars':'Data Processing',
    'datatable':'Data Processing',
    'modin':'Data Processing',
    'vaex':'Data Processing',
    'cupy':'Data Processing',
    'pydantic':'Data Processing',
    
    # Others
    'beautifulsoup4': 'Others',
    'lxml': 'Others',
    'pytest': 'Others',
    'pytest-cov': 'Others',
    'sphinx': 'Others',
    'coverage': 'Others',
    'jupyter': 'Others',
    'notebook': 'Others',
    'ipython': 'Others',
    'pyside2': 'Others',
    'pillow' : 'Others',
    'arrow' : 'Others',
    'bcrypt' : 'Others',
    'cryptography' : 'Others',
    'openai' : 'Others',
    'google-api-core' : 'Others',
    'google-api-python-client' : 'Others',
    'google-auth' : 'Others',
    'google-auth-httplib2' : 'Others',
    'google-auth-oauthlib' : 'Others',
    'google-paster' : 'Others',
    'googleapis-common-protos' : 'Others',
    'future' : 'Others',
    'gitdb' : 'Others',
    'glfw' : 'Others',
    'fonttools' : 'Others',
    'gast' : 'Others',
    'gitpython' : 'Others',
    'googletrans' : 'Others',
    'gym' : 'Others',
    'gym-notice' : 'Others',
    'gymnasium' : 'Others',
    'huggingface-hub' : 'Others',
    'hyperlink' : 'Others',
    'hyperframe' : 'Others',
    'ipykernel' : 'Others',
    'install' : 'Others',
    'jarvis' : 'Others',
    'jupyter_client' : 'Others',
    'jupyter_core' : 'Others',
    'langdetect' : 'Others',
    'dill' : 'Others',
    'email_validator' : 'Others',
    'defer' : 'Others',
    'ipython' : 'Others',
    'language_data' : 'Others',
    'panda' : 'Others',
    'panda3d' : 'Others',
    'pdf2image' : 'Others',
    'pexpect' : 'Others',
    'ptyprocess' : 'Others',
    'youtube-dl' : 'Others',
    'cupy-cuda11x':'Others',
    'cupy-cuda12x':'Others',
    'cupy-rocm-4-3':'Others',
    'cupy-rocm-5-0':'Others',
    
    
    'zipp' : 'Others',
    'zope.interface' : 'Others',
    'yarl' : 'Others',
    'wheel' : 'Others',
    'wolframalpha' : 'Others',
    'wikipedia' : 'Others',
    'werkzeug' : 'Others',
    'pyinstaller' : 'Others',
    'pyinstaller-hooks-contrib' : 'Others',
    'SQLine' : 'Others',
    'pickle' : 'Others',
    'tkinter' : 'Others',
    'pyqt' : 'Others',
    'pygtk' : 'Others',
    'selenium' : 'Others',
    'textblob' : 'Others',
    'gensim' : 'Others',
    'fasttext' : 'Others',
    'arcade' : 'Others',
    'pendulum' : 'Others',
    'threading' : 'Others',
    'pypdf2' : 'Others',
    'pdfminer' : 'Others',
    'pdfplumber' : 'Others',
    'moviepy' : 'Others',
    'librosa' : 'Others',
    'numba' : 'Others',
    'anaconda' : 'Others',
    'pipeenv' : 'Others',
    'atom' : 'Others',
    'cython' : 'Others',
    'networkx' : 'Others',
    'statsmodels' : 'Others',
    'pattern' : 'Others',
    'psycopg2' : 'Others',
    'humanize' : 'Others',
    'pmw' : 'Others',
    'sympy' : 'Others',
    'pytesseract' : 'Others',
    'pywin32' : 'Others',
    'pyserial' : 'Others',
    
    
    
    'cx_oracle' : 'Others',
    'fpdf' : 'Others',
    'signal' : 'Others',
    'opencv': 'Others',
    'pyopengl': 'Others',
    'pyunit': 'Others',
    'behave': 'Others',
    'robot': 'Others',
    'testify': 'Others',
    'lettuce': 'Others',
    'pytest': 'Others',
    'pyspark': 'Others',
    'ray': 'Others',
    'hadoop': 'Others',
    'dask': 'Others',
    'pillow' : 'Others',
    'picologging': 'Others',
    'structlog': 'Others',
    'logbook': 'Others',
    'rich': 'Others',
    'colorama': 'Others',
    'folium': 'Others',
    'pygal': 'Others',
    'altair': 'Others',
    'pymc3': 'Others',
    'theano': 'Others',
    'pystan': 'Others',
    'pingouim': 'Others',
    
    'mechanicalsoup': 'Others',
    'pretty-errors': 'Others',
    'typer': 'Others',
    'icecream': 'Others',
    'beeware': 'Others',
    'ttkbootstrap': 'Others',
    'trio': 'Others',
    'flet':'Others',
    'flet-core':'Others',
    'flet-runtime':'Others',
    'python-apt' : 'Others',
    'python-debian' : 'Others',
    'python-multipart' : 'Others',
    'python-poppler-gt5' : 'Others',
    'python-vlc': 'Others',
    'python-slugify' : 'Others',
    'python3': 'Others',
    'Py2exe':'Others',
    'Pyomo':'Others',
    'NetworkX':'Others',
    'Pandas-profiling':'Others',
    'Tweepy':'Others',
    'Praw':'Others',
    'Boto3':'Others',
    'Multiprocess' : 'Others',
    
    'gspread':'Others',
    'python-docx':'Others',
    'python-pptx':'Others',
    'ReportLab':'Others',
    'WeasyPrint':'Others',
    'Mimesis':'Others',
    'Pytz':'Others',
    'Dateutil':'Others',
    'Pandas-ta':'Others',
    'Backtrader':'Others',
    'PyAlgoTrade':'Others',
    'ccxt':'Others',
    'pandas_datareader ':'Others',
    'mlfinlab':'Others',
    'Empyrical':'Others',
    'Pyfolio':'Others',
    'Quantlib':'Others',
    'Qiskit':'Others',
    'Cirq':'Others',
    'OpenFermion':'Others',
    'Uvicorn':'Others',
    'Daphne':'Others',
    'Hypercorn':'Others',
    'Dramatiq':'Others',
    'Huey':'Others',
    'RQ':'Others',
    'Fakeredis':'Others',
    'Motor':'Others',
    'Tortoise-ORM':'Others',
    'Peewee-async':'Others',
    'Sqlalchemy-aio':'Others',
    'redis-py':'Others',
    'Kombu':'Others',
    'RabbitMQ':'Others',
    'sqlalchemy-utils':'Others',
    'alembic':'Others',
    'Django-extensions':'Others',
    'Django-allauth':'Others',
    'Django-cors-headers':'Others',
    'Django-debug-toolbar':'Others',
    'Django-channels':'Others',
    'Django-rest-auth':'Others',
    'Django-filter ':'Others',
    'Django-haystack':'Others',
    'Django-taggit':'Others',
    'Django-webpack-loade':'Others',
    'nbconvert':'Others',
    'nbformat':'Others',
    'ipywidgets':'Others',
    'papermill':'Others',
    'voila':'Others',
    'streamlit':'Others',
    'Gradio':'Others',
    'dash-cytoscape':'Others',
    'dash-bootstrap-components':'Others',
    'plotly_express':'Others',
    'dash_daq':'Others',
    'dash_core_components':'Others',
    'dash_html_components ':'Others',
    'dash_table -':'Others',
    'dash_bio':'Others',
    'dash_canvas':'Others',
    'dash_code':'Others',
    'dash_vtk':'Others',
    'dash_colorscales':'Others',
    'dash_player':'Others',
    'dash_cytoscape ':'Others',
    'dash':'Others',
    'brotlicffi':'Others',
    'httpcore':'Others',
    'h11':'Others',
    'certifi':'Others',
    'idna':'Others',
    'sniffio':'Others',
    'h2':'Others',
    'socksio':'Others',
    'brotli':'Others',
    'zstandard':'Others',
    'async_timeout':'Others',
    'attrs':'Others',
    'multidict':'Others',
    'tg.devtools':'Others',
    'psutil':'Others',
    '':'Others', 
    '':'Others',





    
    


    
}

MODULE_POPULARITY = {
'numpy': 73.43,
'pandas': 73.58,
'matplotlib': 74.19,
'seaborn': 73.73,
'bokeh': 73.43,
'plotly': 73.58,
'scipy': 73.43,
'statsmodels': 74.34,
'xgboost': 73.73,
'sqlalchemy': 74.19,
'peewee': 73.58,
'pymongo': 73.73,
'redis': 73.43,
'databases': 74.04,
'sqlobject': 74.04,
'arrow': 73.43,
'python-dotenv': 74.65,
'pydantic': 73.89,
'dataclasses': 74.34,
'pyyaml': 73.58,
'hypothesis': 74.19,
'tox': 73.12,
'mock': 73.28,
'pdb': 73.12,
'ipdb': 73.28,
'click': 73.43,
'typer': 73.43,
'loguru': 73.58,
'colorama': 73.89,
'requests': 73.89,
'flask': 73.43,
'django': 73.58,
'fastapi': 73.73,
'tornado': 73.73,
'bottle': 73.58,
'aiohttp': 73.73,
'httpx': 73.43,
'beautifulsoup4': 74.80,
'scrapy': 73.58,
'requests-html': 74.65,
'mechanize': 74.04,
'pyquery': 73.73,
'scrapy-splash': 74.65,
'py2neo': 73.58,
'paramiko': 73.89,
'asyncio': 73.73,
'pygtk': 73.43,
'pyglet': 73.58,
'pyqtgraph': 74.04,
'sh': 72.97,
'websocket-client': 75.10,
'cherrypy': 73.89,
'falcon': 73.58,
'turbogears2': 74.34,
'pyramid': 73.73,
'web2py': 73.58,
'trio-websocket': 74.80,
'scikit-learn': 74.50,
'tensorflow': 74.19,
'keras': 73.43,
'torch': 73.43,
'catboost': 73.89,
'lightgbm': 73.89,
'celery': 73.58,
'textblob': 73.89,
'nltk': 73.28,
'word2vec': 73.89,
'jax': 73.12,
'eli5': 73.28,
'gernism': 73.73,
'spacy': 73.43,
'bert': 73.28,
'polyglot': 73.89,
'transformers': 74.50,
'PyAudio': 73.73,
'pydub': 73.43,
'sounddevice': 74.34,
'pygame': 73.58,
'playsound': 74.04,
'audioread': 74.04,
'pyaudio': 73.73,
'soundfile': 74.04,
'simpleaudio': 74.34,
'wave': 73.28,
'vosk': 73.28,
'SpeechRecognition': 75.26,
'pocketsphinx': 74.50,
'Google Speech-to-Text': 75.87,
'Microsoft Azure Speech Service': 77.24,
'pyttsx3': 73.73,
'gTTS': 73.28,
'pymysql': 73.73,
'redis-py': 73.89,
'happybase': 74.04,
'psycopg2': 73.89,
'twisted': 73.73,
'pysocks': 73.73,
'websockets': 74.19,
'pyopenssl': 74.04,
'yara-python': 74.34,
'scapy': 73.43,
'pycrypto': 73.89,
'bleak': 73.43,
'paho-mqtt': 74.04,
'zigpy': 73.43,
'circiutpython': 74.65,
'micropython': 74.34,
'pyqt5': 73.43,
'tkinter': 73.73,
'customtkinter': 74.65,
'kivy': 73.28,
'pyforms': 73.73,
'pyautogui': 74.04,
'wxpython': 73.89,
'pyside6': 73.73,
'openai': 74.02,
'google-api-core': 73.43,
'google-api-python-client': 72.84,
'google-auth': 73.69,
'google-auth-httplib2': 73.10,
'google-auth-oauthlib': 73.10,
'google-paster': 73.56,
'googleapis-common-protos': 72.84,
'future': 74.02,
'gitdb': 74.09,
'glfw': 74.15,
'fonttools': 73.83,
'gast': 74.15,
'gitpython': 73.83,
'googletrans': 73.69,
'gym': 74.22,
'gymnasium': 73.83,
'huggingface-hub': 73.43,
'hyperlink': 73.83,
'hyperframe': 73.76,
'ipykernel': 73.83,
'install': 73.96,
'jarvis': 74.02,
'jupyter_client': 73.50,
'jupyter_core': 73.63,
'langdetect': 73.76,
'dill': 74.15,
'email_validator': 73.43,
'defer': 74.09,
'language_data': 73.56,
'panda3d': 73.96,
'pdf2image': 73.83,
'pexpect': 73.96,
'ptyprocess': 73.76,
'youtube-dl': 73.76,
'cupy-cuda11x': 73.63,
'cupy-cuda12x': 73.63,
'cupy-rocm-4-3': 73.56,
'cupy-rocm-5-0': 73.56,
'zipp': 74.15,
'zope.interface': 73.50,
'Multiprocess': 72.31,
'yarl': 74.15,
'wheel': 74.09,
'wolframalpha': 73.63,
'wikipedia': 73.83,
'werkzeug': 73.89,
'pyinstaller': 73.69,
'pyinstaller-hooks-contrib': 72.78,
'SQLine': 74.02,
'pickle': 74.02,
'pyqt': 74.15,
'selenium': 73.89,
'textblob': 73.89,
'gensim': 74.02,
'fasttext': 73.89,
'arcade': 74.02,
'pendulum': 73.89,
'multiprocessing': 73.43,
'threading': 73.83,
'pypdf2': 74.02,
'pdfminer': 73.89,
'pdfplumber': 73.76,
'moviepy': 73.96,
'librosa': 73.96,
'numba': 74.09,
'anaconda': 73.89,
'pipenv': 74.02,
'atom': 74.15,
'cython': 74.02,
'networkx': 73.89,
'pattern': 73.96,
'psycopg2': 73.89,
'humanize': 73.89,
'sympy': 74.09,
'pytesseract': 73.69,
'pywin32': 73.96,
'pyserial': 73.89,
'cx_oracle': 73.83,
'fpdf': 74.15,
'signal': 74.02,
'opencv': 74.02,
'pyopengl': 73.89,
'pyunit': 74.02,
'behave': 74.02,
'robot': 74.09,
'testify': 73.96,
'lettuce': 73.96,
'pyspark': 73.96,
'ray': 74.22,
'hadoop': 74.02,
'dask': 74.15,
'picologging': 73.69,
'structlog': 73.83,
'logbook': 73.96,
'rich': 74.15,
'folium': 74.02,
'pygal': 74.09,
'altair': 74.02,
'pymc3': 74.09,
'theano': 74.02,
'pystan': 74.02,
'pingouin': 73.89,
'mechanicalsoup': 73.50,
'pretty-errors': 73.56,
'typer': 74.09,
'icecream': 73.89,
'beeware': 73.96,
'ttkbootstrap': 73.63,
'trio': 74.15,
'flet': 74.15,
'python-apt': 73.76,
'python-debian': 73.56,
'python-multipart': 73.37,
'python-poppler-qt5': 73.23,
'python-vlc': 73.76,
'python-slugify': 73.50,
'python3': 73.96,
'py2exe': 74.02,
'pyomo': 74.09,
'pandas-profiling': 73.37,
'tweepy': 74.02,
'praw': 74.15,
'boto3': 74.09,
'gspread': 73.96,
'python-docx': 73.69,
'python-pptx': 73.69,
'reportlab': 73.83,
'weasyprint': 73.76,
'mimesis': 73.96,
'pytz': 74.15,
'dateutil': 73.89,
'pandas-ta': 73.83,
'backtrader': 73.76,
'pyalgotrade': 73.69,
'ccxt': 74.15,
'pandas_datareader': 73.30,
'mlfinlab': 73.89,
'empyrical': 73.83,
'pyfolio': 73.96,
'quantlib': 73.89,
'qiskit': 74.02,
'cirq': 74.15,
'openfermion': 73.69,
'uvicorn': 73.96,
'daphne': 74.02,
'hypercorn': 73.83,
'Dramatiq': 75.28,
'Huey': 76.58,
'RQ': 77.22,
'Fakeredis': 74.96,
'Motor': 76.25,
'Tortoise-ORM': 73.98,
'Peewee-async': 73.98,
'Sqlalchemy-aio': 73.34,
'redis-py': 75.28,
'Kombu': 76.25,
'RabbitMQ': 75.28,
'sqlalchemy-utils': 72.69,
'alembic': 75.60,
'Django-extensions': 72.36,
'Django-allauth': 73.34,
'Django-cors-headers': 71.72,
'Django-debug-toolbar': 71.39,
'Django-channels': 73.01,
'Django-rest-auth': 72.69,
'Django-filter': 73.66,
'Django-haystack': 73.01,
'Django-taggit': 73.66,
'Django-webpack-loade': 71.39,
'nbconvert': 74.96,
'nbformat': 75.28,
'ipywidgets': 74.63,
'papermill': 74.96,
'voila': 76.25,
'streamlit': 74.96,
'Gradio': 75.93,
'dash-cytoscape': 73.34,
'dash-bootstrap-components': 69.77,
'plotly_express': 73.34,
'dash_daq': 75.28,
'dash_core_components': 71.39,
'dash_html_components': 71.39,
'dash_table': 74.63,
'dash_bio': 75.28,
'dash_canvas': 74.31,
'dash_code': 74.96,
'dash_vtk': 75.28,
'dash_colorscales': 72.69,
'dash_player': 74.31,
'dash_cytoscape': 73.34,
'dash': 76.58,
'brotlicffi': 74.63,
'httpcore': 75.28,
'h11': 76.90,
'certifi': 75.60,
'idna': 76.58,
'sniffio': 75.60,
'h2': 77.22,
'socksio': 75.60,
'brotli': 75.93,
'zstandard': 74.96,
'async_timeout': 73.66,
'attrs': 76.25,
'multidict': 74.96,
'tg.devtools': 74.31,
'psutil': 75.93,




# Add more modules and popularity here
}


MODULE_DOCS = {
    "numpy": "https://numpy.org/doc/",
    "pandas": "https://pandas.pydata.org/pandas-docs/stable/",
    "matplotlib": "https://matplotlib.org/stable/contents.html",
    "scikit-learn": "https://scikit-learn.org/stable/documentation.html",
    "requests": "https://docs.python-requests.org/en/latest/",
    "flask": "https://flask.palletsprojects.com/en/latest/",
    "django": "https://docs.djangoproject.com/en/stable/",
    "tensorFlow": "https://www.tensorflow.org/api_docs",
    "requests": "https://docs.python-requests.org/en/latest/",
    "django": " https://www.djangoproject.com/",
    "fastapi": "https://fastapi.tiangolo.com/",
    "tornado": "https://www.tornadoweb.org/en/stable/",
    "bottle": "https://bottlepy.org/docs/dev/",
    "aiohttp": "https://docs.aiohttp.org/en/stable/",
    "httpx": "https://www.python-httpx.org/",
    "beautifulsoup4": "https://www.crummy.com/software/BeautifulSoup/bs4/doc/",
    "scrapy": " https://docs.scrapy.org/en/latest/",
    "requests-html": "https://requests-html.kennethreitz.org/",
    "mechanize": "https://mechanize.readthedocs.io/",
    "pyquery": "https://pyquery.readthedocs.io/",
    "scrapy-splash": "https://github.com/scrapy-plugins/scrapy-splash",
    
    "py2neo": "https://py2neo.org/",
    "paramiko": " https://www.paramiko.org/",
    "asyncio": " https://docs.python.org/3/library/asyncio.html",
    "pygtk": " https://www.pygtk.org/",
    "pyglet": "https://pyglet.readthedocs.io/en/latest/",
    "pyqtgraph": "https://www.pyqtgraph.org/",
    "sh": "https://amoffat.github.io/sh/",
    "websocket-client": "https://websocket-client.readthedocs.io/",
    "cherrypy": "https://cherrypy.dev/",
    "falcon": "https://falconframework.org/",
    "turbogears2": " https://www.turbogears.org/",
    "pyramid": "https://trypyramid.com/",
    "web2py": "https://www.web2py.com/",
    "trio-websocket": " https://github.com/python-trio/trio-websocket",
    "polars": " https://www.pola.rs/",
    "datatable": " https://datatable.readthedocs.io/",
    "modin": "https://modin.readthedocs.io/",
    "vaex": "https://vaex.io/",
    "cupy": "https://cupy.dev/",
    "pydantic": "https://pydantic-docs.helpmanual.io/",
    "pyqt5": "https://www.riverbankcomputing.com/software/pyqt/intro",
    "tkinter": " https://docs.python.org/3/library/tkinter.html",
    "customtkinter": "https://github.com/TomSchimansky/CustomTkinter",
    "kivy": "https://kivy.org/",
    "pyforms": "https://pyforms.readthedocs.io/",
    "pyautogui": "https://pyautogui.readthedocs.io/",
    "wxpython": "https://wxpython.org/",
    "pyside6": "https://www.qt.io/qt-for-python",
    "transformers": "https://huggingface.co/transformers/",
    "bert": " https://github.com/google-research/bert",
    "genisum": "https://pypi.org/project/genisum/",
    "eli5": "https://eli5.readthedocs.io/",
    
    "jax": "https://jax.readthedocs.io/",
    "word2vec": "https://code.google.com/archive/p/word2vec/",
    "nltk": " https://www.nltk.org/",
    "textblob": " https://textblob.readthedocs.io/",
    "celery": "https://docs.celeryproject.org/",
    "fastapi": "https://fastapi.tiangolo.com/",
    "lightgbm": "https://lightgbm.readthedocs.io/",
    "catboost": "https://catboost.ai",
    "torch": " https://pytorch.org/",
    "keras": " https://keras.io/",
    "tensorflow": "https://www.tensorflow.org/",
    "Sanic":" https://sanic.dev/",
    "Quart":" https://quart.readthedocs.io/",
    "faker":"https://faker.readthedocs.io/",
    "xgboost":" https://xgboost.readthedocs.io/",
    "openpyxl":" https://openpyxl.readthedocs.io/",
    "pyexcel":"https://pyexcel.readthedocs.io/",
    "holoviews":" https://holoviews.org/",
    "google-cloud-firestore":"https://googleapis.dev/python/firestore/latest/index.html",
    "google-cloud-storage":"https://googleapis.dev/python/storage/latest/index.html",
    "nacl":"https://pynacl.readthedocs.io/",
    "pycryptodome":"https://www.pycryptodome.org/",
    "dash_daq":"https://dash.plotly.com/dash-daq",
    "dash_core_components":"https://dash.plotly.com/dash-core-components",
    "dash_html_components":"https://dash.plotly.com/dash-html-components",
    "dash_table":"https://dash.plotly.com/dash-table",
    "dash_bio":"https://dash.plotly.com/dash-bio",
    "dash_canvas":"https://github.com/plotly/dash-canvas",
    "dash_code":"https://github.com/plotly/dash-code",
    "dash_vtk":"https://github.com/plotly/dash-vtk",
    "dash_colorscales":" https://pypi.org/project/dash_colorscales/",
    "dash_playe":"https://github.com/plotly/dash-player",
    "dash_cytoscape":"https://dash.plotly.com/dash-cytoscape",
    "mechanicalsoup":"https://mechanicalsoup.readthedocs.io",
    "pretty-errors":" https://pypi.org/project/pretty-errors/",
    "typer":"https://typer.tiangolo.com",
    "typer":"https://beeware.org",
    "ttkbootstrap":"https://ttkbootstrap.readthedocs.io",
    "trio":" https://trio.readthedocs.io",
    "flet":"https://flet.dev",
    "flet-core":"https://pypi.org/project/flet-core/",
    "flet-runtime":" https://pypi.org/project/flet-runtime/",
    "python-apt":" https://wiki.debian.org/Python/Apt",
    "python-debian":" https://python-debian.readthedocs.io",
    "python-multipart":"https://kludex.github.io/python-multipart/",
    "python-poppler-gt5":" https://pypi.org/project/python-poppler/",
    "python-vlc":"https://www.videolan.org/vlc/python.html",
    "python-slugify":" https://github.com/un33k/python-slugify",
    "python3":" https://www.python.org",

    "cx_Oracle":"https://oracle.github.io/python-cx_Oracle",
    "fpdf":"http://www.fpdf.org",
    "pyopengl":"http://pyopengl.sourceforge.net",
    "opencv":" https://opencv.org",
    "behave":" https://behave.readthedocs.io",
    "robot":"https://robotframework.org",
    "testify":"https://github.com/testify/testify",
    "lettuce":" https://lettuce.readthedocs.io",
    "pytest":"https://pytest.org",
    "pyspark":"https://spark.apache.org/docs/latest/api/python/",
    "ray":"https://www.ray.io",
    "hadoop":"https://hadoop.apache.org",
    "pillow":" https://pillow.readthedocs.io",
    "picologging":"https://microsoft.github.io/picologging/",
    "structlog":"https://www.structlog.org",
    "logbook":"https://logbook.readthedocs.io",
    "rich":" https://rich.readthedocs.io",
    "folium":"https://folium.readthedocs.io",
    "pygal":"http://www.pygal.org",
    "altair":"https://altair-viz.github.io",
    "pymc3":"https://docs.pymc.io",
    "theano":"http://deeplearning.net/software/theano",
    "pystan":"https://pystan.readthedocs.io",
    "pingouin":"https://pingouin-stats.org",
    "pyserial":"https://pyserial.readthedocs.io",
    "pywin32":" https://github.com/mhammond/pywin32",
    "pytesseract":" https://github.com/madmaze/pytesseract",
    "sympy":" https://www.sympy.org",
    "pmw":"https://pmw.sourceforge.net",
    "humanize":"https://github.com/jmoiron/humanize",
    "psycopg2":" https://www.psycopg.org",
    "pattern":"https://www.clips.uantwerpen.be/pattern",
    "statsmodels":"https://www.statsmodels.org",
    "cython":" https://cython.org",
    "networkx":" https://networkx.org",
    "atom":"https://atom.io",
    "pipeenv":"https://github.com/pypa/pipeenv",
    "anaconda":"https://www.anaconda.com",
    "numba":"http://numba.pydata.org",
    "librosa":" https://librosa.org",
    "moviepy":" https://zulko.github.io/moviepy",

    "pdfplumber":" https://github.com/jsvine/pdfplumber",
    "pdfminer":" https://pdfminers.org",
    "pypdf2":" https://github.com/py-pdf/pypdf2",
    "pygtk":"https://pygobject.gnome.org/",
    "pyqt":"https://wiki.python.org/moin/PyQt",
    "pyinstaller-hooks-contrib":"https://github.com/pyinstaller/pyinstaller-hooks-contrib",
    "pyinstaller":"https://www.pyinstaller.org",
    "werkzeug":"https://werkzeug.palletsprojects.com",
    "wikipedia":" https://wikipedia.readthedocs.io",
    "wolframalpha":"https://github.com/wolframalpha/wolframalpha-python",
    "wheel":"https://wheel.readthedocs.io",
    "yarl":"https://yarl.readthedocs.io",
    "zope.interface":" https://zopeinterface.readthedocs.io",
    "zipp":" https://zipp.readthedocs.io",
    "coverage":"https://coverage.readthedocs.io",
    "beautifulsoup4":"https://www.crummy.com/software/BeautifulSoup",
    "lxml":"https://lxml.de",
    "pytest":"https://docs.pytest.org",
    "pytest-cov":"https://pytest-cov.readthedocs.io",
    "sphinx":" https://www.sphinx-doc.org",
    "jupyter":" https://jupyter.org",
    "notebook":"https://jupyter-notebook.readthedocs.io",
    "ipython":"https://ipython.readthedocs.io",
    "pyside2":"https://wiki.qt.io/Qt_for_Python",
    "pillow":"https://python-pillow.org",
    "bcrypt":" https://pypi.org/project/bcrypt",
    "cryptography":"https://cryptography.io",
    "openai":"https://github.com/openai/openai-python",
    "google-api-core":" https://github.com/googleapis/python-api-core",
    "google-api-python-client":"https://github.com/googleapis/google-api-python-client",
    "google-auth":"https://github.com/googleapis/google-auth-library-python",
    "google-auth-httplib2":" https://github.com/googleapis/google-auth-library-python-httplib2",
    "google-auth-oauthlib":" https://github.com/googleapis/google-auth-library-python-oauthlib",
    "googleapis-common-protos":" https://github.com/googleapis/python-api-common-protos",
    "future":"https://python-future.org",
    "gitdb":"https://github.com/gitpython-developers/gitdb",
    
    "glfw":" https://www.glfw.org",
    "fonttools":"https://fonttools.readthedocs.io",
    "gast":"https://github.com/serge-sans-paille/gast",
    "gitpython":"https://github.com/gitpython-developers/GitPython",
    "googletrans":"https://github.com/ssut/py-googletrans",
    "gym":" https://www.gymlibrary.ml",
    "gymnasium":"https://gymnasium.farama.org",
    "huggingface-hub":" https://huggingface.co",
    "hyperlink":"https://hyperlink.readthedocs.io",
    "hyperframe":"https://github.com/python-hyper/hyperframe",
    "ipykernel":" https://ipykernel.readthedocs.io",
    "jarvis":"https://github.com/sukeesh/Jarvis",
    "jupyter_client":" https://github.com/jupyter/jupyter_client",
    "jupyter_core":"https://github.com/jupyter/jupyter_core",
    "langdetect":"https://github.com/Mimino666/langdetect",
    "dill":"https://github.com/uqfoundation/dill",
    "email_validator":"https://github.com/JoshData/python-email-validator",
    "defer":"https://github.com/twisted/twisted",
    "panda3d":"https://www.panda3d.org",
    "pdf2image":"https://github.com/Belval/pdf2image",
    "pexpect":" https://pexpect.readthedocs.io",
    "ptyprocess":"https://ptyprocess.readthedocs.io",
    "youtube-dl":"https://ytdl-org.github.io/youtube-dl",
    "language_data":"https://pypi.org/project/language-data/",
    "brotlicffi":"https://pypi.org/project/brotlicffi/",
    "httpcore":"https://pypi.org/project/httpcore/",
    "zipp":"https://zipp.readthedocs.io/en/latest/",
    "nltk" : "https://www.nltk.org/",
    "bert" : "https://huggingface.co/docs/transformers/en/model_doc/bert",
    "audioread" : "https://pypi.org/project/audioread/",
    "torch" : "https://pytorch.org/",
    "bokeh" : "https://docs.bokeh.org/en/latest/",
    "" : "",
    "" : "",
    
    
    
    




    
    # Machine Learning
    "scikit-learn": "https://scikit-learn.org/",
    "colorama": " https://pypi.org/project/colorama/",
    "loguru": " https://loguru.readthedocs.io/",
    "typer": "https://typer.tiangolo.com/",
    "click": "https://click.palletsprojects.com/",
    "ipdb": "https://ipdb.readthedocs.io/",
    "mock": "https://docs.python.org/3/library/unittest.mock.html",
    "tox": "https://tox.readthedocs.io/",
    
    "hypothesis": " https://hypothesis.readthedocs.io/",
    "pyyaml": " https://pyyaml.org/",
    "dataclasses": "https://docs.python.org/3/library/dataclasses.html",
    "python-dotenv": " https://github.com/theskumar/python-dotenv",
    "arrow": "https://arrow.readthedocs.io/",
    "sqlobject": " http://sqlobject.org/",
    "databases": "https://www.encode.io/databases/",
    "redis": "https://redis-py.readthedocs.io/",
    "pymongo": " https://pymongo.readthedocs.io/",
    "peewee": " http://docs.peewee-orm.com/",
    "sqlalchemy": " https://www.sqlalchemy.org/",
    "xgboost": "https://xgboost.readthedocs.io/",
    "statsmodels": "https://www.statsmodels.org/",
    "scipy": "https://scipy.org/",
    "plotly": " https://plotly.com/",
    
    # Sound Output
    
    "PyAudio": "https://people.csail.mit.edu/hubert/pyaudio/",
    "pydub": " https://pydub.com/",
    "sounddevice": "https://python-sounddevice.readthedocs.io/",
    "pygame": "https://www.pygame.org/",
    "playsound": "https://github.com/TaylorSMarks/playsound",
    "audioread": " https://audioread.readthedocs.io/",
    "pyaudio": "https://people.csail.mit.edu/hubert/pyaudio/",
    "soundfile": "https://pysoundfile.readthedocs.io",
    "simpleaudio": "https://simpleaudio.readthedocs.io/",
    "wave": " https://docs.python.org/3/library/wave.html",
    "vosk": "https://alphacephei.com/vosk/",
    
    
    
    
    #Speech Recognition (Speech-to-Text)
    
    "SpeechRecognition": " https://pypi.org/project/SpeechRecognition/",
    "pocketsphinx": " https://github.com/cmusphinx/pocketsphinx",
    "Google Speech-to-Text": "https://cloud.google.com/speech-to-text",
    "Microsoft Azure Speech Services": "https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/",
   
    
    #Speech Synthesis (Text-to-Speech)
    
    "pyttsx3": "https://pyttsx3.readthedocs.io/",
    "gTTS": " https://gtts.readthedocs.io/",
    "pico2wave": "https://github.com/VitalPBX/pico2wave",
    
    #Databases
    
    "pymysql": "https://pymysql.readthedocs.io/",
    "redis-py": "https://redis-py.readthedocs.io/",
    "happybase": " https://happybase.readthedocs.io/",
    "psycopg2": "https://www.psycopg.org/",
    "sqlalchemy": "https://www.sqlalchemy.org/",

    #Networking
    
    "twisted":"https://twistedmatrix.com/trac/",
    "pysocks":"https://github.com/Anorov/PySocks",
    "websockets":"https://websockets.readthedocs.io/",
    "requests":"https://requests.readthedocs.io/",
    "httpx":"https://www.python-httpx.org/",
    
    #GUI's 
    
    "tkinter":"https://wiki.python.org/moin/TkInter",
    "wxPython":" https://www.wxpython.org/",
    "PyGTK":" https://www.pygtk.org/",
    "PyQt":"https://riverbankcomputing.com/software/pyqt/intro",
    
    #Web Frameworks
    "Flask":"https://flask.palletsprojects.com/",
    "Django":"https://www.djangoproject.com/",
    "FastAPI":"https://fastapi.tiangolo.com/",
    "":"",
    "":"",
    "":"",
    "":"",
    
    # Add more modules as needed
}

MODULE_DEPENDENCIES = {
    'numpy': ['scipy', 'mkl'],
    'pandas': ['numpy', 'python-dateutil', 'pytz'],
    'matplotlib': ['numpy', 'pyparsing', 'cycler'],
    'requests': ['certifi', 'charset-normalizer', 'idna', 'urllib3'],
    'pyqt5' : ['pyqt5-tools', 'sip'],
    'jupyter' : ['notebook', 'jupyter_core', 'jupyter_client', 'ipython-genutils'],
    'flet' : ['flet-core', 'flet-runtime'],
    'google-api-core' : ['google-api-python-client', 'google-auth', 'google-auth-oauthlib2','google-pasta', 'googleapis-common-protos', 'googletrans'],
    'opencv': ['opencv-contrib-python', 'opencv-python'],
    'pyopengl': ['pyopenql-accelerate'],
    'pyside6' : ['pyside6_addons', 'pyside6_essential'],
    'django': ["Django-extensions","Django-allauth ","Django-cors-headers",
               "Django-debug-toolbar" ,"Django-channels",
               "Django-rest-auth", "Django-filter", "Django-haystack", 
               "Django-taggit","Django-webpack-loade"],
    'sqlalchemy' : ["sqlalchemy-utils", "sqlalchemy-aio", "",],
    'dash' : ["dash-cytoscape ", "dash-bootstrap-components ", "dash_daq", "dash_core_components",
               "dash_html_components",  "dash_table",  "dash_bio",  "dash_canvas",
               "dash_code", "dash_vtk - 3D", "dash_colorscales ", "dash_player", "dash_cytoscape"],
    'cupy':["cupy-cuda11x", "cupy-cuda12x", "cupy-rocm-4-3", "cupy-rocm-5-0"],
    'vaex' : ["vaex-core", "vaex-hdf5",  "vaex-arrow",  "vaex-viz",  "vaex-jupyter",
              "vaex-astro", "vaex-server", "vaex-distributed", "vaex-qt", "vaex-ml"],
    'httpx' : ["httpcore", "h11", "certifi", "idna", "sniffio", "h2",  "socksio",
               "rich", "click", "brotli", "brotlicffi", ], 
    'aiohttp' : ["attrs",  "multidict", "yarl", "aiodns", "Brotli", "async_timeout",],
    'turbogears2': ["tg.devtools"],
    # Add more modules and their dependencies as needed
}